// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPEbmOdrv9y8B1eMf-ssbxwYSqanyNxw',
    appId: '1:323123791884:web:f96dcead809cde99474629',
    messagingSenderId: '323123791884',
    projectId: 'whatsapp-99f81',
    authDomain: 'whatsapp-99f81.firebaseapp.com',
    storageBucket: 'whatsapp-99f81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMWH5TcFiS_cSijZGn2F9m3kk_lYkMBM',
    appId: '1:323123791884:android:4de42f6a5572124b474629',
    messagingSenderId: '323123791884',
    projectId: 'whatsapp-99f81',
    storageBucket: 'whatsapp-99f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfkrLR9wWs_z1fRKxo2qeu9ylIXYQW2A',
    appId: '1:323123791884:ios:dded643eae9384ea474629',
    messagingSenderId: '323123791884',
    projectId: 'whatsapp-99f81',
    storageBucket: 'whatsapp-99f81.appspot.com',
    iosClientId: '323123791884-j10n7bb7l419ne6s7q22tloupt9nu33d.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
